# Generated by Django 5.0 on 2023-12-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='textIntegral',
            new_name='text_integral',
        ),
    ]
