# Generated by Django 5.0 on 2023-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_textintegral_article_text_integral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_integral',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencebibliographique',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
