# Generated by Django 5.0 on 2024-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
