# Generated by Django 5.0 on 2023-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_uploadedarticle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedarticle',
            name='file',
            field=models.FileField(upload_to='articles/'),
        ),
    ]
