# Generated by Django 5.0 on 2023-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_alter_uploadedarticle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebibliographique',
            name='nom',
            field=models.CharField(max_length=500),
        ),
    ]
