# Generated by Django 5.0 on 2023-12-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_alter_referencebibliographique_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebibliographique',
            name='nom',
            field=models.CharField(max_length=2000),
        ),
    ]
