# Generated by Django 5.0 on 2024-02-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_article_is_validated'),
        ('Articles', '0008_alter_referencebibliographique_nom'),
    ]

    operations = [
    ]
