# Generated by Django 5.0 on 2023-12-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_alter_referencebibliographique_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='prenom',
        ),
    ]
