# Generated by Django 5.0 on 2024-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_merge_20240202_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_de_publication',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_integral',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='nom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='referencebibliographique',
            name='nom',
            field=models.TextField(),
        ),
    ]
