# Generated by Django 5.0 on 2023-12-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_remove_auteur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_integral',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='referencebibliographique',
            name='nom',
            field=models.TextField(),
        ),
    ]
