# Generated by Django 5.0 on 2023-12-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0010_alter_article_resume_alter_article_text_integral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publication',
            field=models.DateField(null=True),
        ),
    ]
