# Generated by Django 5.0 on 2023-12-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_alter_article_date_de_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_integral',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='nom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='text',
            field=models.TextField(),
        ),
    ]
